name: marcus_evans_2024
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - solas-ai
    - PiML
    - xgboost
    - fastparquet
    - notebook
    - matplotlib
    - jupyter
    - ipywidgets
    - openpyxl
    - pyarrow
    - rich
